### ISSUE TITLE
do you plan any updates for this list ?

### ISSUE THREAD

**Issue by whiletrue111** [rafaskb/awesome-libgdx#52]
its 4 years old

**Comment by rafaskb** [comment]
The list is 4 years old, but the latest commit was done just 5 months ago. This list has become mature and stable, and there is no need to constantly update it, as new libraries aren't created that quickly anyway.

New and experimental libraries are shared and discussed in the libGDX Discord, and when they become mature enough, and if their authors wish so, PRs are created to add them to this list, and community feedback and input is expected in such PRs in order to validate their "awesomeness". That's how we keep the list curated.

As far as maintainability goes, we're often updating links to make sure they're always up-to-date.
